### ISSUE TITLE
Can I use it in a Keras model?

### ISSUE THREAD

**Issue by ntelo007** [cpuimage/clDice#1]
Hi,

I would like to ask you if I can use your loss function in a Keras model. I tried to use it but I am facing some errors already. I also had to convert it to TensorFlow v1 instead of v2.

**Comment by cpuimage** [comment]
@ntelo007  try this code
`
def norm_intersection(center_line, vessel):
    intersection = tf.reduce_sum(center_line * vessel, axis=(1, 2, 3), keepdims=True)
    return tf.compat.v1.div_no_nan(intersection, tf.reduce_sum(center_line, axis=(1, 2, 3), keepdims=True))


def dilation2d(x, kernel_size=3, dilations=1, strides=1):
    kernel = np.asarray(np.ones([kernel_size, kernel_size]), np.float32)
    kernel = kernel.reshape(list(kernel.shape) + [1, 1])
    kernel = np.tile(kernel, [1, 1, np.shape(x)[-1], 1]) / (kernel_size * kernel_size)
    y = tf.compat.v1.nn.dilation2d(padding_tensor(x, kernel_size),
                                   filter=tf.constant(np.squeeze(kernel, -1) - 1. / (kernel_size * kernel_size),
                                                      tf.float32),
                                   strides=[1, strides, strides, 1], padding="VALID",
                                   rates=[1, dilations, dilations, 1])
    return y


def erosion2d(x, kernel_size=3, dilations=1, strides=1):
    kernel = np.asarray(np.ones([kernel_size, kernel_size]), np.float32)
    kernel = kernel.reshape(list(kernel.shape) + [1, 1])
    kernel = np.tile(kernel, [1, 1, np.shape(x)[-1], 1]) / (kernel_size * kernel_size)
    y = tf.compat.v1.nn.erosion2d(padding_tensor(x, kernel_size),
                                  kernel=tf.constant(np.squeeze(kernel, -1) - 1. / (kernel_size * kernel_size),
                                                     tf.float32),
                                  strides=[1, strides, strides, 1], padding="VALID",
                                  rates=[1, dilations, dilations, 1])
    return y


def soft_skeletonize(x, thresh_width=10, kernel_size=3, dilations=1):
    for i in range(thresh_width):
        min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
        contour = tf.nn.relu(dilation2d(min_pool_x, kernel_size=kernel_size, dilations=dilations) - min_pool_x)
        x = tf.nn.relu(x - contour)
    return x


def soft_cldice_loss(predictions, labels, label_skeleton=None, thresh_width=10):
    pred_skeleton = soft_skeletonize(predictions, thresh_width=thresh_width)
    if label_skeleton is None:
        label_skeleton = soft_skeletonize(labels, thresh_width=thresh_width)
    iflat = norm_intersection(pred_skeleton, labels)
    tflat = norm_intersection(label_skeleton, predictions)
    ret = 1. - tf.compat.v1.div_no_nan(2. * iflat * tflat, iflat + tflat)
    return tf.reshape(ret, (-1, 1, 1))
`

**Comment by ntelo007** [comment]
Thanks for your quick reply!

From the snippet above I get the following:

```
Undefined variable 'padding_tensor'
```

**Comment by cpuimage** [comment]
@ntelo007 
```
def padding_tensor(x, patch_size=3):
    paddings = tf.constant([[0, 0], [int((patch_size - 1) / 2), int((patch_size - 1) / 2)],
                            [int((patch_size - 1) / 2), int((patch_size - 1) / 2)], [0, 0]])
    return tf.pad(x, paddings, "REFLECT")

**Comment by ntelo007** [comment]
@cpuimage 
I tried to compile my model with what you provided and this is the error I get:
```
Traceback (most recent call last):
  File ".\unet_resnet.py", line 374, in <module>
    model.compile(optimizer, total_loss, metrics)
  File "C:\Users\...\anaconda3\lib\site-packages\keras\engine\training.py", line 342, in compile
    sample_weight, mask)
  File "C:\Users\...\anaconda3\lib\site-packages\keras\engine\training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "C:\Users\...\soft_clDice_loss.py", line 47, in soft_cldice_loss
    pred_skeleton = soft_skeletonize(predictions, thresh_width=thresh_width)
  File "C:\Users\...\soft_clDice_loss.py", line 40, in soft_skeletonize
    min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
  File "C:\Users\...\soft_clDice_loss.py", line 29, in erosion2d
    kernel = np.tile(kernel, [1, 1, np.shape(x)[-1], 1]) / (kernel_size * kernel_size)
  File "C:\Users\...\anaconda3\lib\site-packages\numpy\lib\shape_base.py", line 1243, in tile
    return c.reshape(shape_out)
TypeError: __index__ returned non-int (type NoneType)
```

**Comment by cpuimage** [comment]
@ntelo007
```
def padding_tensor(x, patch_size=3):
    paddings = tf.constant([[0, 0], [int((patch_size - 1) / 2), int((patch_size - 1) / 2)],
                            [int((patch_size - 1) / 2), int((patch_size - 1) / 2)], [0, 0]])
    return tf.pad(x, paddings, "REFLECT")


def norm_intersection(center_line, vessel):
    intersection = tf.reduce_sum(center_line * vessel, axis=(1, 2, 3), keepdims=True)
    return tf.compat.v1.div_no_nan(intersection, tf.reduce_sum(center_line, axis=(1, 2, 3), keepdims=True))


def dilation2d(x, kernel_size=3, dilations=1, strides=1):
    kernel = tf.zeros([kernel_size, kernel_size, x.get_shape().as_list()[-1]], tf.float32)
    y = tf.compat.v1.nn.dilation2d(padding_tensor(x, kernel_size),
                                   filter=kernel,
                                   strides=[1, strides, strides, 1], padding="VALID",
                                   rates=[1, dilations, dilations, 1])
    return y


def erosion2d(x, kernel_size=3, dilations=1, strides=1):
    kernel = tf.zeros([kernel_size, kernel_size, x.get_shape().as_list()[-1]], tf.float32)
    y = tf.compat.v1.nn.erosion2d(padding_tensor(x, kernel_size),
                                  kernel=kernel,
                                  strides=[1, strides, strides, 1], padding="VALID",
                                  rates=[1, dilations, dilations, 1])
    return y


def fixed_soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1):
    for _ in tf.range(0, maximum_iterations):
        min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
        contour = tf.nn.relu(dilation2d(min_pool_x, kernel_size=kernel_size, dilations=dilations) - min_pool_x)
        x = tf.nn.relu(x - contour)
    return x


def soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1, threshold=1.):
    def body(_, skelitonize):
        eroded = erosion2d(skelitonize, kernel_size=kernel_size, dilations=dilations)
        skelitonize = tf.nn.relu(
            skelitonize - tf.nn.relu(dilation2d(eroded, kernel_size=kernel_size, dilations=dilations) - eroded))
        return [eroded, skelitonize]

    def cond(prev_eroded, _):
        return tf.reduce_any(tf.reduce_sum(prev_eroded, (1, 2, 3)) > threshold)

    _, h, w, c = x.get_shape().as_list()
    shape_invariants = [x.get_shape(), tf.TensorShape([None, h, w, c])]
    _, x = tf.compat.v1.while_loop(cond=cond,
                                   body=body,
                                   shape_invariants=shape_invariants,
                                   maximum_iterations=maximum_iterations,
                                   loop_vars=[x, x])
    return x

def soft_cldice_losses(y_true, y_pred, true_skeleton=None, maximum_iterations=10, fixed_iterations=False):
    if fixed_iterations:
        soft_skeletonize_func = fixed_soft_skeletonize
    else:
        soft_skeletonize_func = soft_skeletonize
    pred_skeleton = soft_skeletonize_func(y_pred, maximum_iterations=maximum_iterations)
    if true_skeleton is None:
        true_skeleton = soft_skeletonize_func(y_true, maximum_iterations=maximum_iterations)
    iflat = norm_intersection(pred_skeleton, y_true)
    tflat = norm_intersection(true_skeleton, y_pred)
    loss = 1. - tf.compat.v1.div_no_nan(2. * iflat * tflat, iflat + tflat)
    return loss

**Comment by ntelo007** [comment]
@cpuimage 

The new error now:
```
Traceback (most recent call last):
  File ".\unet_resnet.py", line 374, in <module>
    model.compile(optimizer, soft_clDice_loss, metrics)
  File "C:\Users\...\anaconda3\lib\site-packages\keras\engine\training.py", line 342, in compile
    sample_weight, mask)
  File "C:\Users\...\anaconda3\lib\site-packages\keras\engine\training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "C:\Users\...\soft_clDice_loss.py", line 48, in soft_cldice_loss
    pred_skeleton = soft_skeletonize(predictions, thresh_width=thresh_width)
  File "C:\Users\...\soft_clDice_loss.py", line 41, in soft_skeletonize
    min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
  File "C:\Users\...\soft_clDice_loss.py", line 30, in erosion2d
    kernel = tf.reshape(kernel, (list(tf.shape(kernel)) + [1, 1]))
  File "C:\Users\...\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 477, in __iter__
    "Tensor objects are only iterable when eager execution is "
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
```

**Comment by cpuimage** [comment]
@ntelo007 replace that line  to
```
kernel = tf.reshape(kernel, (kernel.get_shape().as_list() + [1, 1]))

**Comment by ntelo007** [comment]
@cpuimage  
Seems like it's working now. Have you used this loss function before? Do you have comparable results? Or just implemented the loss function for practice?

**Comment by cpuimage** [comment]
@ntelo007 only for a little practice. it run much times,so slow.

**Comment by ntelo007** [comment]
@cpuimage  I will give it a try. Thanks for your quick responses.

**Comment by cpuimage** [comment]
@ntelo007  have a good luck.

**Comment by ntelo007** [comment]
@cpuimage Do you happen to use it in combination with a soft dice loss?

**Comment by cpuimage** [comment]
@ntelo007  no,i didn't do that.

**Comment by ntelo007** [comment]
I trained a road detection U-Net with a ResNet34 encoder and these are the results:

![cldice_output](https://user-images.githubusercontent.com/31326655/80288856-2b730580-873b-11ea-88cc-6882c635751a.png)
![cldice_dice_outputt](https://user-images.githubusercontent.com/31326655/80288857-2e6df600-873b-11ea-95d9-675c76d1ca19.png)

In the first figure, you can see the prediction of just using clDice loss function. The second prediction was calculated by a network trained with clDice + dice loss. Any ideas?

**Comment by cpuimage** [comment]
@ntelo007 
The effect depends on the ground truth,
You may be able to use dynamic iteration to train,
adjustment maximum_iterations and threshold to fit the datasets.

code show as below:
```
def soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1, threshold=1.):
    def body(_, skelitonize):
        eroded = erosion2d(skelitonize, kernel_size=kernel_size, dilations=dilations)
        skelitonize = tf.nn.relu(
            skelitonize - tf.nn.relu(dilation2d(eroded, kernel_size=kernel_size, dilations=dilations) - eroded))
        return [eroded, skelitonize]

    def cond(prev_eroded, _):
        return tf.reduce_any(tf.reduce_sum(prev_eroded, (1, 2, 3)) > threshold)

    _, x = tf.while_loop(cond=cond,
                         body=body,
                         maximum_iterations=maximum_iterations,
                         loop_vars=[x, x])
    return x

**Comment by ntelo007** [comment]
So far I am using this code:

```
import tensorflow as tf

def padding_tensor(x, patch_size=3):
    paddings = tf.constant([[0, 0], [int((patch_size - 1) / 2), int((patch_size - 1) / 2)],
                            [int((patch_size - 1) / 2), int((patch_size - 1) / 2)], [0, 0]])
    return tf.pad(x, paddings, "REFLECT")


def norm_intersection(center_line, vessel):
    intersection = tf.reduce_sum(center_line * vessel, axis=(1, 2, 3), keepdims=True)
    return tf.compat.v1.div_no_nan(intersection, tf.reduce_sum(center_line, axis=(1, 2, 3), keepdims=True))


def dilation2d(x, kernel_size=3, dilations=1, strides=1):
    weight = 1. / (kernel_size * kernel_size)
    kernel = tf.ones([kernel_size, kernel_size], tf.float32)
    # kernel = tf.reshape(kernel, (list(tf.shape(kernel)) + [1, 1]))
    kernel = tf.reshape(kernel, (kernel.get_shape().as_list() + [1, 1]))

    kernel = tf.tile(kernel, [1, 1, tf.shape(x)[-1], 1]) * weight
    y = tf.compat.v1.nn.dilation2d(padding_tensor(x, kernel_size),
                                   filter=tf.squeeze(kernel, -1) - weight,
                                   strides=[1, strides, strides, 1], padding="VALID",
                                   rates=[1, dilations, dilations, 1])
    return y


def erosion2d(x, kernel_size=3, dilations=1, strides=1):
    weight = 1. / (kernel_size * kernel_size)
    kernel = tf.ones([kernel_size, kernel_size], tf.float32)
    # kernel = tf.reshape(kernel, (list(tf.shape(kernel)) + [1, 1]))
    kernel = tf.reshape(kernel, (kernel.get_shape().as_list() + [1, 1]))
    kernel = tf.tile(kernel, [1, 1, tf.shape(x)[-1], 1]) * weight
    y = tf.compat.v1.nn.erosion2d(padding_tensor(x, kernel_size),
                                  kernel=tf.squeeze(kernel, -1) - weight,
                                  strides=[1, strides, strides, 1], padding="VALID",
                                  rates=[1, dilations, dilations, 1])
    return y


def soft_skeletonize(x, thresh_width=10, kernel_size=3, dilations=1):
    for i in range(thresh_width):
        min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
        contour = tf.nn.relu(dilation2d(min_pool_x, kernel_size=kernel_size, dilations=dilations) - min_pool_x)
        x = tf.nn.relu(x - contour)
    return x


def soft_cldice_loss(predictions, labels, label_skeleton=None, thresh_width=10):
    pred_skeleton = soft_skeletonize(predictions, thresh_width=thresh_width)
    if label_skeleton is None:
        label_skeleton = soft_skeletonize(labels, thresh_width=thresh_width)
    iflat = norm_intersection(pred_skeleton, labels)
    tflat = norm_intersection(label_skeleton, predictions)
    ret = 1. - tf.compat.v1.div_no_nan(2. * iflat * tflat, iflat + tflat)
    return tf.reshape(ret, (-1, 1, 1))

def dice_loss(y_true, y_pred):
  numerator = 2 * tf.reduce_sum(y_true * y_pred, axis=(1,2,3))
  denominator = tf.reduce_sum(y_true + y_pred, axis=(1,2,3))

  return 1 - numerator / denominator

def combined_loss(y_true, y_pred):
    return dice_loss(y_true, y_pred) + soft_cldice_loss(y_pred, y_true)

```

Should I replace my soft_skeletonize function with what you provided?

**Comment by cpuimage** [comment]
@ntelo007 if the maximum_iterations and threshold fit your data sets, you can do that.

**Comment by ntelo007** [comment]
@cpuimage  What does it mean 'fit your data sets'? How can I test that?

**Comment by cpuimage** [comment]
@ntelo007 replace the code,and train a while,then check the results.

**Comment by ntelo007** [comment]
@cpuimage What should I provide as input in my soft_clDice_loss function now that I have replace the soft_skeletonize function? Just predictions and labels and remove the threshold_width? The definition of the soft_clDice_loss is given above in the code I pasted.

**Comment by cpuimage** [comment]
@ntelo007 
```
def fixed_soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1):
    for _ in tf.range(0, maximum_iterations):
        min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
        contour = tf.nn.relu(dilation2d(min_pool_x, kernel_size=kernel_size, dilations=dilations) - min_pool_x)
        x = tf.nn.relu(x - contour)
    return x


def soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1, threshold=1.):
    def body(_, skelitonize):
        eroded = erosion2d(skelitonize, kernel_size=kernel_size, dilations=dilations)
        skelitonize = tf.nn.relu(
            skelitonize - tf.nn.relu(dilation2d(eroded, kernel_size=kernel_size, dilations=dilations) - eroded))
        return [eroded, skelitonize]

    def cond(prev_eroded, _):
        return tf.reduce_any(tf.reduce_sum(prev_eroded, (1, 2, 3)) > threshold)

    _, x = tf.while_loop(cond=cond,
                         body=body,
                         maximum_iterations=maximum_iterations,
                         loop_vars=[x, x])
    return x


def soft_cldice_losses(y_true, y_pred, true_skeleton=None, maximum_iterations=10, fixed_iterations=False):
    if fixed_iterations:
        soft_skeletonize_func = fixed_soft_skeletonize
    else:
        soft_skeletonize_func = soft_skeletonize
    pred_skeleton = soft_skeletonize_func(y_pred, maximum_iterations=maximum_iterations)
    if true_skeleton is None:
        true_skeleton = soft_skeletonize_func(y_true, maximum_iterations=maximum_iterations)
    iflat = norm_intersection(pred_skeleton, y_true)
    tflat = norm_intersection(true_skeleton, y_pred)
    loss = 1. - tf.compat.v1.div_no_nan(2. * iflat * tflat, iflat + tflat)
    return loss

**Comment by ntelo007** [comment]
I receive the following Traceback error:

```
Traceback (most recent call last):
  File "unet_resnet.py", line 293, in <module>
    model.compile(optimizer, total_loss, metrics)
  File ".../python3.6/site-packages/keras/engine/training.py", line 342, in compile
    sample_weight, mask)
  File ".../python3.6/site-packages/keras/engine/training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File ".../soft_clDice_loss.py", line 103, in soft_cldice_losses
    pred_skeleton = soft_skeletonize_func(y_pred, maximum_iterations=maximum_iterations)
  File ".../soft_clDice_loss.py", line 95, in soft_skeletonize
    loop_vars=[x, x])
  File ".../python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File ".../python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File ".../python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3059, in _BuildLoop
    next_vars.append(_AddNextAndBackEdge(m, v))
  File ".../python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 677, in _AddNextAndBackEdge
    _EnforceShapeInvariant(m, v)
  File ".../python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 620, in _EnforceShapeInvariant
    "less-specific shape." % (input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'softmax/truediv:0' enters the loop with shape (?, 256, 256, 2), but has shape (?, 256, 256, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.
```

**Comment by cpuimage** [comment]
@ntelo007  
```
  _, x = tf.while_loop(cond=cond,
                         body=body,
                         shape_invariants=[x.get_shape(), x.get_shape()],
                         maximum_iterations=maximum_iterations,
                         loop_vars=[x, x])

**Comment by ntelo007** [comment]
The error is the same:
  ```
"less-specific shape." % (input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'softmax/truediv:0' enters the loop with shape (?, 256, 256, 2), but has shape (?, 256, 256, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.``

**Comment by cpuimage** [comment]
@ntelo007  
maybe this way.
```
  _, x = tf.while_loop(cond=cond,
                         body=body,
                         shape_invariants=[x.get_shape().as_list(), x.get_shape().as_list()],
                         maximum_iterations=maximum_iterations,
                         loop_vars=[x, x])

**Comment by ntelo007** [comment]
Didn't work either:

```
Traceback (most recent call last):
  File "unet_resnet.py", line 408, in <module>
    model.compile(optimizer, total_loss, metrics)
  File "C:\Users\...\site-packages\keras\engine\training.py", line 342, in compile
    sample_weight, mask)
  File "C:\Users\...\site-packages\keras\engine\training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "C:\Users\...\soft_clDice_loss.py", line 104, in soft_cldice_losses
    pred_skeleton = soft_skeletonize_func(y_pred, maximum_iterations=maximum_iterations)
  File "C:\Users\...\soft_clDice_loss.py", line 96, in soft_skeletonize
    loop_vars=[x, x])
  File "C:\Users\...\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3484, in while_loop
    loop_vars, shape_invariants, expand_composites=False)
  File "C:\Users\...\site-packages\tensorflow\python\util\nest.py", line 304, in assert_same_structure
    % (str(e), str1, str2))
ValueError: The two structures don't have the same nested structure.

First structure: type=tuple str=(<tf.Tensor 'loss/softmax_loss/while/iteration_counter:0' shape=() dtype=int32>, [<tf.Tensor 'softmax/truediv:0' shape=(?, 256, 256, 2) dtype=float32>, <tf.Tensor 'softmax/truediv:0' shape=(?, 256, 256, 2) dtype=float32>])

Second structure: type=tuple str=(TensorShape([]), [[None, 256, 256, 2], [None, 256, 256, 2]])

More specifically: Substructure "type=list str=[None, 256, 256, 2]" is a sequence, while substructure "type=Tensor str=Tensor("softmax/truediv:0", shape=(?, 256, 256, 2), dtype=float32)" is not
Entire first structure:
(., [., .])
Entire second structure:
(., [[., ., ., .], [., ., ., .]])
```

**Comment by cpuimage** [comment]
@ntelo007 
```
def combined_static_and_dynamic_shape(tensor):
    """Returns a list containing static and dynamic values for the dimensions.
    Returns a list of static and dynamic values for shape dimensions. This is
    useful to preserve static shapes when available in reshape operation.
    Args:
      tensor: A tensor of any type.
    Returns:
      A list of size tensor.shape.ndims containing integers or a scalar tensor.
    """
    static_tensor_shape = tensor.shape.as_list()
    dynamic_tensor_shape = tf.shape(tensor)
    combined_shape = []
    for index, dim in enumerate(static_tensor_shape):
        if dim is not None:
            combined_shape.append(dim)
        else:
            combined_shape.append(dynamic_tensor_shape[index])
    return combined_shape

 _, x = tf.while_loop(cond=cond,
                         body=body,
                         shape_invariants=[combined_static_and_dynamic_shape(x) , combined_static_and_dynamic_shape(x)],
                         maximum_iterations=maximum_iterations,
                         loop_vars=[x, x])

**Comment by ntelo007** [comment]
@cpuimage 

I incorporated your snippet and this is how it looks now:
```
def fixed_soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1):
    for _ in tf.range(0, maximum_iterations):
        min_pool_x = erosion2d(x, kernel_size=kernel_size, dilations=dilations)
        contour = tf.nn.relu(dilation2d(min_pool_x, kernel_size=kernel_size, dilations=dilations) - min_pool_x)
        x = tf.nn.relu(x - contour)
    return x

def soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1, threshold=1.):
    def body(_, skelitonize):
        eroded = erosion2d(skelitonize, kernel_size=kernel_size, dilations=dilations)
        skelitonize = tf.nn.relu(
            skelitonize - tf.nn.relu(dilation2d(eroded, kernel_size=kernel_size, dilations=dilations) - eroded))
        return [eroded, skelitonize]

    def cond(prev_eroded, _):
        return tf.reduce_any(tf.reduce_sum(prev_eroded, (1, 2, 3)) > threshold)

    def combined_static_and_dynamic_shape(tensor):
        '''
        Returns a list containing static and dynamic values for the dimensions.
        Returns a list of static and dynamic values for shape dimensions. This is
        useful to preserve static shapes when available in reshape operation.
        Args:
        tensor: A tensor of any type.
        Returns:
        A list of size tensor.shape.ndims containing integers or a scalar tensor.
        '''
        static_tensor_shape = tensor.shape.as_list()
        dynamic_tensor_shape = tf.shape(tensor)
        combined_shape = []
        for index, dim in enumerate(static_tensor_shape):
            if dim is not None:
                combined_shape.append(dim)
            else:
                combined_shape.append(dynamic_tensor_shape[index])
        return combined_shape

    _, x = tf.while_loop(cond=cond,
                            body=body,
                            shape_invariants=[combined_static_and_dynamic_shape(x) , combined_static_and_dynamic_shape(x)],
                            maximum_iterations=maximum_iterations,
                            loop_vars=[x, x])

    return x

def soft_cldice_losses(y_true, y_pred, true_skeleton=None, maximum_iterations=10, fixed_iterations=False):
    if fixed_iterations:
        soft_skeletonize_func = fixed_soft_skeletonize
    else:
        soft_skeletonize_func = soft_skeletonize
    pred_skeleton = soft_skeletonize_func(y_pred, maximum_iterations=maximum_iterations)
    if true_skeleton is None:
        true_skeleton = soft_skeletonize_func(y_true, maximum_iterations=maximum_iterations)
    iflat = norm_intersection(pred_skeleton, y_true)
    tflat = norm_intersection(true_skeleton, y_pred)
    loss = 1. - tf.compat.v1.div_no_nan(2. * iflat * tflat, iflat + tflat)
    return loss
```

Unfortunately, I receive this error message:
```
File "C:\Users\...\site-packages\tensorflow\python\util\nest.py", line 304, in assert_same_structure
    % (str(e), str1, str2))
ValueError: The two structures don't have the same nested structure.

First structure: type=tuple str=(<tf.Tensor 'loss/softmax_loss/while/iteration_counter:0' shape=() dtype=int32>, [<tf.Tensor 'softmax/truediv:0' shape=(?, 256, 256, 2) dtype=float32>, <tf.Tensor 'softmax/truediv:0' shape=(?, 256, 256, 2) dtype=float32>])

Second structure: type=tuple str=(TensorShape([]), [[<tf.Tensor 'loss/softmax_loss/strided_slice:0' shape=() dtype=int32>, 256, 256, 2], [<tf.Tensor 'loss/softmax_loss/strided_slice_1:0' shape=() dtype=int32>, 256, 256, 2]])

More specifically: Substructure "type=list str=[<tf.Tensor 'loss/softmax_loss/strided_slice:0' shape=() dtype=int32>, 256, 256, 2]" is a sequence, while substructure "type=Tensor str=Tensor("softmax/truediv:0", shape=(?, 256, 256, 2), dtype=float32)" is not
Entire first structure:
(., [., .])
Entire second structure:
(., [[., ., ., .], [., ., ., .]])
```

**Comment by cpuimage** [comment]
@ntelo007 

```
def soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1, threshold=1.):
    def body(_, skelitonize):
        eroded = erosion2d(skelitonize, kernel_size=kernel_size, dilations=dilations)
        skelitonize = tf.nn.relu(
            skelitonize - tf.nn.relu(dilation2d(eroded, kernel_size=kernel_size, dilations=dilations) - eroded))
        return [eroded, skelitonize]

    def cond(prev_eroded, _):
        return tf.reduce_any(tf.reduce_sum(prev_eroded, (1, 2, 3)) > threshold)

    _, h, w, c = x.get_shape().as_list()
    shape_invariants = [x.get_shape(), tf.TensorShape([None, h, w, c])]
    _, x = tf.compat.v1.while_loop(cond=cond,
                                   body=body,
                                   shape_invariants=shape_invariants,
                                   maximum_iterations=maximum_iterations,
                                   loop_vars=[x, x])
    return x

**Comment by ntelo007** [comment]
@cpuimage now we came back to this error:
```
ValueError: Input tensor 'softmax/truediv:0' enters the loop with shape (?, 256, 256, 2), but has shape (?, 256, 256, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.
```

**Comment by cpuimage** [comment]
@ntelo007 i think that is a bug.
try to call "set_shape([None, h, w, c])" in while-body directly
```
def soft_skeletonize(x, maximum_iterations=10, kernel_size=3, dilations=1, threshold=1.):
    _, h, w, c = x.get_shape().as_list()

    def body(_, skelitonize):
        eroded = erosion2d(skelitonize, kernel_size=kernel_size, dilations=dilations)
        skelitonize = tf.nn.relu(
            skelitonize - tf.nn.relu(dilation2d(eroded, kernel_size=kernel_size, dilations=dilations) - eroded))
        skelitonize.set_shape([None, h, w, c])
        eroded.set_shape([None, h, w, c])
        return [eroded, skelitonize]

    def cond(prev_eroded, _):
        return tf.reduce_any(tf.reduce_sum(prev_eroded, (1, 2, 3)) > threshold)

    shape_invariants = [x.get_shape(), tf.TensorShape([None, h, w, c])]
    _, x = tf.compat.v1.while_loop(cond=cond,
                                   body=body,
                                   shape_invariants=shape_invariants,
                                   maximum_iterations=maximum_iterations,
                                   loop_vars=[x, x])
    return x

**Comment by ntelo007** [comment]
@cpuimage with your last snippet, it seems that it can run, but using the clDice loss alone, starts from very low levels of loss values (e.g. 0.07). I combined it with a dice loss now and it starts from 0.40. Seems reasonable. I will train it again and get back to you with the results.

**Comment by cpuimage** [comment]
@ntelo007 good job.

**Comment by ntelo007** [comment]
@cpuimage  Same outcome...

![clDice_same_problem](https://user-images.githubusercontent.com/31326655/80790671-c599da00-8b8f-11ea-82ef-3a5852f6230a.png)

**Comment by cpuimage** [comment]
@ntelo007  from the outcome, and @dmitrysarov say's that "Try first to overfit your model on a small dataset (it can be several images, but not one if you use batchnorm). If the model is able to remember small dataset labels, then move to the evaluation of the validation procedure."
pre-calculateda all the ground truth's skelitonize to warm-up training weights is better then dynamic skelitonize.

**Comment by ntelo007** [comment]
@cpuimage What is the difference if I train a network with this loss function on a small subset of my dataset or with the whole dataset? The output that I receive is very strange, which means that the calculation of the skeleton is not proper. I already have centerline ground truth images that correspond to the training dataset. Why would they be beneficial?

**Comment by cpuimage** [comment]
@ntelo007 the skeleton of each single mask is different.If the same number of iterations is used, part of the skeleton information will be lost.so it is difficult to set a reasonable threshold to suit the dataset,the idea of this loss algorithm is similar to edge detection.If the model can fit the skeleton well, it will be beneficial to the overall training.
